<?xml version="1.0"?>
<!--
License: Apache 2.0. See LICENSE file in root directory.
Copyright(c) 2017 Intel Corporation. All Rights Reserved

This is the URDF model for the Intel RealSense 415 camera, in its
aluminum peripherial evaluation case.
-->

<robot name="sensor_d405" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Includes -->

  <xacro:include filename="$(find realsense2_description)/urdf/_usb_plug.urdf.xacro" />

  <xacro:macro name="sensor_d405"
               params="parent *origin  name:=camera  use_nominal_extrinsics:=false add_plug:=false use_mesh:=true attach_at_bottom:=true">

    <!-- The following values are approximate, and the camera node
     publishing TF values with actual calibrated camera extrinsic values -->
    <xacro:property name="d405_cam_depth_to_infra1_offset" value="0.009"/>
    <xacro:property name="d405_cam_depth_to_infra2_offset" value="-0.009"/>
    <!-- Color stream from left imager -->
    <xacro:property name="d405_cam_depth_to_color_offset" value="-0.009"/>

    <!-- The following values model the aluminum peripherial case for the
  	d405 camera, with the camera joint represented by the actual
  	peripherial camera tripod mount -->
    <xacro:property name="d405_cam_width" value="0.042"/>
    <xacro:property name="d405_cam_height" value="0.042"/>
    <xacro:property name="d405_cam_depth" value="0.023"/>
    <xacro:property name="d405_cam_mount_from_center_offset" value="0.00835"/>
    <xacro:property name="d405_cam_mount_from_front" value=".01465"/>

    <!-- The following offset is relative the  physical d405 camera peripheral
  	camera tripod mount -->
    <!-- Distance from mount to front glass, minus front glass to depth origin (via datasheet) -->
    <xacro:property name="d405_cam_depth_px" value="${d405_cam_mount_from_front - 0.0027}"/>
    <xacro:property name="d405_cam_depth_py" value="0"/>
    <xacro:property name="d405_cam_depth_pz" value="${d405_cam_height/2}"/>


    <!-- camera body, with origin at bottom screw mount -->
    <link name="${name}_bottom_screw_frame"/>
    <xacro:if value="${attach_at_bottom}">
      <joint name="${name}_joint" type="fixed">
        <xacro:insert_block name="origin"/>
        <parent link="${parent}"/>
        <child link="${name}_bottom_screw_frame"/>
      </joint>
    </xacro:if>
    <xacro:unless value="${attach_at_bottom}">
      <!-- Other frames are set up to descend from the bottom screw. So that we don't have to change
              everything, we'll just add an imaginary "adapter bracket" that accepts the connection from
              the caller transforms it from the center of the back mount down to the screw point. -->
      <link name="${name}_back_to_bottom_shim"/>
      <joint name="${name}_adapter_joint" type="fixed">
        <xacro:insert_block name="origin"/>
        <parent link="${parent}"/>
        <child link="${name}_back_to_bottom_shim"/>
      </joint>
      <joint name="${name}_joint" type="fixed">
        <origin xyz=".00835 0 -.021236" rpy="0 0 0"/>
        <parent link="${name}_back_to_bottom_shim"/>
        <child link="${name}_bottom_screw_frame"/>
      </joint>
    </xacro:unless>


    <joint name="${name}_link_joint" type="fixed">
      <origin xyz="${d405_cam_depth_px} ${d405_cam_depth_py} ${d405_cam_depth_pz}" rpy="0 0 0"/>
      <parent link="${name}_bottom_screw_frame"/>
      <child link="${name}_link" />
    </joint>

    <link name="${name}_link">
      <visual>
        <xacro:if value="${use_mesh}">
          <origin xyz="${-d405_cam_depth_px} 0 ${-d405_cam_height / 2}" rpy="0 0 0 "/>
          <geometry>
            <mesh filename="package://tahoma_description/meshes/d405.dae" />
          </geometry>
          <material name="aluminum"/>
        </xacro:if>
        <xacro:unless value="${use_mesh}">
          <origin xyz="0 ${-d405_cam_depth_py} 0" rpy="0 0 0"/>
          <geometry>
            <box size="${d405_cam_depth} ${d405_cam_width} ${d405_cam_height}"/>
          </geometry>
        </xacro:unless>
      </visual>
      <collision>
        <origin xyz="${-d405_cam_depth + d405_cam_mount_from_front} ${-d405_cam_depth_py} 0" rpy="0 0 0"/>
        <geometry>
        <box size="${d405_cam_depth} ${d405_cam_height} ${d405_cam_width}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.072" />
        <!-- The following are not reliable values, and should not be used for modeling -->
        <origin xyz="0 0 0" />
        <inertia ixx="0.003881243" ixy="0.0" ixz="0.0" iyy="0.000498940" iyz="0.0" izz="0.003879257" />
      </inertial>
    </link>

    <!-- Use the nominal extrinsics between camera frames if the calibrated extrinsics aren't being published. e.g. running the device in simulation  -->
    <xacro:if value="${use_nominal_extrinsics}">
      <!-- camera depth joints and links -->
      <joint name="${name}_depth_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="${name}_link"/>
        <child link="${name}_depth_frame" />
      </joint>
      <link name="${name}_depth_frame"/>

      <joint name="${name}_depth_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
        <parent link="${name}_depth_frame" />
        <child link="${name}_depth_optical_frame" />
      </joint>
      <link name="${name}_depth_optical_frame"/>

      <!-- camera left IR joints and links -->
      <joint name="${name}_infra1_joint" type="fixed">
        <origin xyz="0 ${d405_cam_depth_to_infra1_offset} 0" rpy="0 0 0" />
        <parent link="${name}_link" />
        <child link="${name}_infra1_frame" />
      </joint>
      <link name="${name}_infra1_frame"/>

      <joint name="${name}_infra1_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
        <parent link="${name}_infra1_frame" />
        <child link="${name}_infra1_optical_frame" />
      </joint>
      <link name="${name}_infra1_optical_frame"/>

      <!-- camera right IR joints and links -->
      <joint name="${name}_infra2_joint" type="fixed">
        <origin xyz="0 ${d405_cam_depth_to_infra2_offset} 0" rpy="0 0 0" />
        <parent link="${name}_link" />
        <child link="${name}_infra2_frame" />
      </joint>
      <link name="${name}_infra2_frame"/>

      <joint name="${name}_infra2_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
        <parent link="${name}_infra2_frame" />
        <child link="${name}_infra2_optical_frame" />
      </joint>
      <link name="${name}_infra2_optical_frame"/>

      <!-- camera color joints and links -->
      <joint name="${name}_color_joint" type="fixed">
        <origin xyz="0 ${d405_cam_depth_to_color_offset} 0" rpy="0 0 0" />
        <parent link="${name}_link" />
        <child link="${name}_color_frame" />
      </joint>
      <link name="${name}_color_frame"/>

      <joint name="${name}_color_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
        <parent link="${name}_color_frame" />
        <child link="${name}_color_optical_frame" />
      </joint>
      <link name="${name}_color_optical_frame"/>
    </xacro:if>

    <xacro:if value="${add_plug}">
      <xacro:usb_plug parent="${name}_link" name="${name}_usb_plug">
        <origin xyz="${d405_cam_mount_from_center_offset - 0.01587} ${-d405_cam_depth_py - 0.0358} 0" rpy="0 0 0"/>
      </xacro:usb_plug>
    </xacro:if>
  </xacro:macro>
</robot>
