# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  arm_elbow_joint:
    max_position: 3.1415926535897931
    min_position: -3.1415926535897931
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: false
    max_acceleration: 0
  arm_shoulder_lift_joint:
    max_position: 3.1415926535897931
    min_position: -3.1415926535897931
    has_velocity_limits: true
    max_velocity: 2.0943951023931953
    has_acceleration_limits: false
    max_acceleration: 0
  arm_shoulder_pan_joint:
    max_position: 3.1415926535897931
    min_position: -3.1415926535897931
    has_velocity_limits: true
    max_velocity: 2.0943951023931953
    has_acceleration_limits: false
    max_acceleration: 0
  arm_wrist_1_joint:
    max_position: 3.1415926535897931
    min_position: -3.1415926535897931
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: false
    max_acceleration: 0
  arm_wrist_2_joint:
    max_position: 3.1415926535897931
    min_position: -3.1415926535897931
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: false
    max_acceleration: 0
  arm_wrist_3_joint: 
    max_position: 3.1415926535897931
    min_position: -3.1415926535897931.
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: false
    max_acceleration: 0