<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="tahoma">
  <xacro:include filename="$(find ur_description)/urdf/inc/ur16e_macro.xacro"/>
  <xacro:include filename="$(find tahoma_description)/urdf/stand.xacro"/>
  <xacro:include filename="$(find robotiq_2f_85_gripper_visualization)/urdf/robotiq_arg2f_85_macro.xacro"/>

  <xacro:include filename="$(find realsense2_description)/urdf/_l515.urdf.xacro"/>

  <xacro:arg name="realsense" default="true"/>
  <xacro:arg name="camera_baseline" default=".5"/>
  <xacro:arg name="camera_focal_depth" default="1.4"/>
  <xacro:arg name="transmission_hw_interface" default="hardware_interface/EffortJointInterface"/>

  <xacro:stand/>
  <xacro:ur16e_robot prefix="arm_"/>
  <xacro:robotiq_arg2f_85
          prefix="gripper_"
          transmission_hw_interface="$(arg transmission_hw_interface)"/>

  <link name="base_link"/>
  <joint name="base_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0.15"/>
    <parent link="base_link"/>
    <child link="stand"/>
  </joint>

  <joint name="robot_plate_arm_base_link_joint" type="fixed">
    <parent link="robot_plate"/>
    <child link="arm_base_link"/>
    <origin rpy="0 ${pi} ${1.5 * pi}" xyz="0 0.00175 -0.00885"/>
  </joint>


  <link name="coupling">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
      <geometry>
        <mesh filename="package://tahoma_description/meshes/robotiq_gripper_coupling.stl"/>
      </geometry>
      <material name="">
        <color rgba="0.1 0.1 0.1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius=".0375" length=".0139"/>
      </geometry>
    </collision>
  </link>

  <joint name="coupling_link_gripper_robotiq_arg2f_base_link_joint" type="fixed">
    <origin xyz="0 0 0.012" rpy="0 0 ${pi/2}"/>
    <parent link="coupling"/>
    <child link="gripper_base_link"/>
  </joint>

  <joint name="arm_tool0-coupling_joint" type="fixed">
    <parent link="arm_tool0"/>
    <child link="coupling"/>
  </joint>

  <link name="camera_lower_right_mount"/>
  <joint name="camera_beam_lower_camera_lower_right_mount_joint" type="fixed">
    <parent link="camera_beam_lower"/>
    <child link="camera_lower_right_mount"/>
    <origin xyz="-0.00 ${-0.0215 + -$(arg camera_baseline) / 2} 0.09"
            rpy="${-pi / 2} 0 ${math.atan2(($(arg camera_baseline) /2),$(arg camera_focal_depth))}"/>
  </joint>

  <link name="camera_lower_left_mount"/>
  <joint name="camera_beam_lower_camera_lower_left_mount_joint" type="fixed">
    <parent link="camera_beam_lower"/>
    <child link="camera_lower_left_mount"/>
    <!-- Link is centered on the optical frames. Slight offset in Y direction to compensate -->
    <origin xyz="-0.00 ${-0.0215 + $(arg camera_baseline) / 2} 0.09"
            rpy="${-pi / 2} 0 ${-math.atan2(($(arg camera_baseline) /2),$(arg camera_focal_depth))}"/>
  </joint>

  <xacro:sensor_l515 name="camera_lower_right" parent="camera_lower_right_mount" use_nominal_extrinsics="true">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:sensor_l515>

  <xacro:sensor_l515 name="camera_lower_left" parent="camera_lower_left_mount" use_nominal_extrinsics="true">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:sensor_l515>

</robot>


