sensor_msgs/PointCloud2 points
float32 dist_th
int8 pose_id
int8 grasp_id
---
bool success
string message
float32 pos_x
float32 pos_y
float32 pos_z
float32 rot_x
float32 rot_y
float32 rot_z
float32 grasp