#!/usr/bin/env python3
import rospy
from sensor_msgs.msg import JointState
from std_msgs.msg import Header

rospy.init_node("fake_gripper_state")
pub = rospy.Publisher("/joint_states", JointState, queue_size=1)

fake_state = JointState(name=['gripper_finger_joint'], position=[0.81], velocity=[0], effort=[0])
rate = rospy.Rate(30)
while not rospy.is_shutdown():
    fake_state.header.stamp = rospy.Time.now()
    pub.publish(fake_state)
    rate.sleep()